class CompletionRequest:
    def __init__(self,
                 model,
                 file_content,
                 cursor_position,
                 language=None,
                 max_tokens=64):
        self.model = model
        self.file_content = file_content
        self.cursor_position = cursor_position
        self.language = language
        # max_tokens: Limits the number of tokens generated by the model
        self.max_tokens = max_tokens